### PR TITLE
If we fail to enter presence due to token capabilities, fetch new token and retry

### LINKED ISSUE #311: Request new auth token when channel attach fails due to permission failure
Only for client instances which are using token auth, not basic auth...

When an operation fails against the embedded `AblyRealtime` instance that is indicative of a service-side permissions issue (i.e. capability to perform the operation against the Ably channel is denied) then the SDK should request a new auth token.

We definitely need this for publishers.

We need to investigate whether this needs to also be implemented for subscribers.

See [this Slack comment (internal)](https://ably-real-time.slack.com/archives/C01QU436CSZ/p1655900418554909?thread_ts=1655884714.683019&cid=C01QU436CSZ) for the recorded Zoom discussion between @paddybyers, @KacperKluka, @ikbalkaya, @AndyNicks, @stmoreau and myself. It covers the reasons for taking this approach, plus how it might intersect with a future engineering effort to add an API that would allow a new auth token to be supplied to the publisher instance on addition or removal of a trackable.

This issue has been created for this SDK representing the same functionality outlined in https://github.com/ably/ably-asset-tracking-android/issues/695.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-2083) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by lawrence-forooghian**
This closes #311. Please review commit-by-commit; there's lots of information in the commit messages.

For anyone just passing by, it's worth noting that this introduces a new piece of tooling (https://github.com/krzysztofzablocki/Sourcery). Opinions welcome.

### CODE REVIEW

**Comment by lawrence-forooghian** [comment]
@KacperKluka - if you're planning on reviewing, probably only the last commit is interesting to you 🙂

**Comment by lawrence-forooghian** [comment]
OK, GitHub doesn't like the fact that I've pushed an 80MB file (the Sourcery binary). Will re-think that approach.

> remote: warning: See http://git.io/iEPt8g for more information.
> remote: warning: File Sourcery/bin/sourcery is 80.84 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
> remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.

**Review by arturjaworski — APPROVED** [review]

**Review by KacperKluka — COMMENTED** [review]
I only looked at the `DefaultAbly` changes and they look good :+1: I'm not an iOS dev, therefore I'll leave this as a comment instead of an approve :wink: 

One thing that you might consider adding is an integration test that verifies this behaviour in a real scenario. While developing this feature in the AAT Android, an integration test revealed a problem with `ably-java` that was breaking this feature (local tests were passing but in the CI they were failing). :wink:

**Comment by lawrence-forooghian** [comment]
> One thing that you might consider adding is an integration test that verifies this behaviour in a real scenario.

@KacperKluka Perhaps you didn't see them, but that’s what the tests in `Tests/SystemTests/PublisherAuthenticationSystemTests.swift` and `Tests/SystemTests/SubscriberAuthenticationSystemTests.swift` are doing. They use the real Ably SDK and first supply it with a token with the incorrect capabilities, and then upon retry of token fetch, supply it with a token with the correct capabilities.

**Pull request merged**
