### PR TITLE
Remove swiftlint build phase script

### PR DESCRIPTION
**Pull request by lukasz-szyszkowski**

### CODE REVIEW

**Review by maratal — APPROVED** [review]
It looks like it does what it does - removing build phase script for swiftlint in the example app. As soon as it is what was intended, I'm being far from the context of this changes, approve this PR.

**Comment by lukasz-szyszkowski** [comment]
> It looks like it does what it does - removing build phase script for swiftlint in the example app. As soon as it is what was intended, I'm being far from the context of this changes, approve this PR.

Yes, it was intended. We don't need to maintain linting in example apps.

**Comment by lawrence-forooghian** [comment]
Hey @lukasz-szyszkowski, I'm wondering why you think we should remove SwiftLint from the example apps? I've seen your [comment on #240](https://github.com/ably/ably-asset-tracking-swift/pull/240#issuecomment-1005409320) and [here](https://github.com/ably/ably-asset-tracking-swift/pull/241#issuecomment-1008578564) that we don't need to lint example app code. But I think we should aspire for our example apps to be a good example of how to write Swift code in general, so I'd suggest we should maintain the linting of the example apps.

I also didn't fully understand the other reason you mentioned in your comment on #240:

> SPM Mapbox versions inconsistency

I understand that this inconsistency prevents us from invoking SwiftLint using `swift run`, which you'd wanted to add to a pre-commit hook, but I don't see why it prevents us from using SwiftLint the same way as we currently are (i.e. by directly invoking the tool).

**Review by lawrence-forooghian — COMMENTED** [review]
Hey @lukasz-szyszkowski, I'm wondering why you think we should remove SwiftLint from the example apps? I've seen your [comment on #240](https://github.com/ably/ably-asset-tracking-swift/pull/240#issuecomment-1005409320) and [here](https://github.com/ably/ably-asset-tracking-swift/pull/241#issuecomment-1008578564) that we don't need to lint example app code. But I think we should aspire for our example apps to be a good example of how to write Swift code in general, so I'd suggest we should maintain the linting of the example apps.

I also didn't fully understand the other reason you mentioned in your comment on #240:

> SPM Mapbox versions inconsistency

I understand that this inconsistency prevents us from invoking SwiftLint using `swift run`, which you'd wanted to add to a pre-commit hook, but I don't see why it prevents us from using SwiftLint the same way as we currently are (i.e. by directly invoking the tool).

**Comment by lukasz-szyszkowski** [comment]
> Hey @lukasz-szyszkowski, I'm wondering why you think we should remove SwiftLint from the example apps? I've seen your [comment on #240](https://github.com/ably/ably-asset-tracking-swift/pull/240#issuecomment-1005409320) and [here](https://github.com/ably/ably-asset-tracking-swift/pull/241#issuecomment-1008578564) that we don't need to lint example app code. But I think we should aspire for our example apps to be a good example of how to write Swift code in general, so I'd suggest we should maintain the linting of the example apps.
> 
> I also didn't fully understand the other reason you mentioned in your comment on #240:
> 
> > SPM Mapbox versions inconsistency
> 
> I understand that this inconsistency prevents us from invoking SwiftLint using `swift run`, which you'd wanted to add to a pre-commit hook, but I don't see why it prevents us from using SwiftLint the same way as we currently are (i.e. by directly invoking the tool).

Ok, you convinced me. Since `Example Apps` are our we should take care that code is written with best practices.

I'm closing this PR.

**Pull request closed without merging**
