### PR TITLE
Remove swiftlint comments

### PR DESCRIPTION
**Pull request by lukasz-szyszkowski**

### CODE REVIEW

**Review by lawrence-forooghian — COMMENTED** [review]
Hi @lukasz-szyszkowski, there's nothing in the PR description or commit messages to explain the motivation behind this changes, so it's quite hard to review. Please could you add some explanation?

**Comment by lukasz-szyszkowski** [comment]
> Hi @lukasz-szyszkowski, there's nothing in the PR description or commit messages to explain the motivation behind these changes, so it's quite hard to review. Please could you add some explanation?

I linked an [issue](https://github.com/ably/ably-asset-tracking-swift/issues/105) to this PR

**Comment by lawrence-forooghian** [comment]
> > Hi @lukasz-szyszkowski, there's nothing in the PR description or commit messages to explain the motivation behind these changes, so it's quite hard to review. Please could you add some explanation?
> 
> I linked an [issue](https://github.com/ably/ably-asset-tracking-swift/issues/105) to this PR

That issue explains the commit "Remove swiftlint comments", but not "Remove swiftlint build phase script". What's the motivation behind the latter?

**Comment by lukasz-szyszkowski** [comment]
> That issue explains the commit "Remove swiftlint comments", but not "Remove swiftlint build phase script". What's the motivation behind the latter?

I've added it because `assemble` GH Action didn't want to pass after removing `swiftlint` config comments. Before you ask :) I'll completely remove swiftlint from the project. There are at least 2 reasons:
1. [SPM Mapbox versions inconsistency](https://github.com/ably/ably-asset-tracking-swift/issues/210#issuecomment-997681743)
2. Example apps don't have to be checked with an additional tool like `swiftlint`

I've created PR which removes `swiftlint` from the build phase of example apps. https://github.com/ably/ably-asset-tracking-swift/pull/241

**Comment by lukasz-szyszkowski** [comment]
In case of this https://github.com/ably/ably-asset-tracking-swift/pull/241#issuecomment-1015140278 I'm closing this PR

**Comment by lawrence-forooghian** [comment]
@lukasz-szyszkowski do we not want to fix the original issue #105, though?

**Pull request closed without merging**
