### PR TITLE
Move appropriate location rendering functional from example app to the SDK

### PR DESCRIPTION
**Pull request by lukasz-szyszkowski**

### CODE REVIEW

**Review by KacperKluka — APPROVED** [review]
LGTM :+1:

**Review by maratal — APPROVED** [review]

**Comment by lukasz-szyszkowski** [comment]
> Hey @lukasz-szyszkowski, please could you explain a bit about the motivation behind this one? Does the Android SDK include similar functionality?

Most of my PRs have an issue linked to them in the `Development` section on this site https://github.com/ably/ably-asset-tracking-swift/issues/262

> Also, if we're going to add a new package, it needs to be documented I think.

sure, I forgot about it

**Comment by lukasz-szyszkowski** [comment]
> > Hey @lukasz-szyszkowski, please could you explain a bit about the motivation behind this one? Does the Android SDK include similar functionality?
> 
> Most of my PRs have an issue linked to them in the `Development` section on this site #262
> 
> > Also, if we're going to add a new package, it needs to be documented I think.
> 
> sure, I forgot about it

added here 60cc9fd2cb3744e33f3e916e33b984f7d0c3b1ac

**Review by KacperKluka — APPROVED** [review]

**Review by lawrence-forooghian — COMMENTED** [review]
I'll wait for #289 to be merged before reviewing this one.

**Comment by JakubJankowski** [comment]
I'd update the `Contributing.md` as well:
```
The product of this project are two libraries:

- `AblyAssetTrackingSubscriber`
- `AblyAssetTrackingPublisher`

defined in the `Package.swift` file
```
Looks like it'll be three libraries now.

**Review by JakubJankowski — APPROVED** [review]

**Review by arturjaworski — APPROVED** [review]

**Pull request merged**
