### PR TITLE
Add docs workflow

### PR DESCRIPTION
**Pull request by QuintinWillison**

### CODE REVIEW

**Comment by QuintinWillison** [comment]
This pull request will remain in Draft state until we can work out why the build is failing. [Here](https://github.com/ably/ably-asset-tracking-cocoa/pull/130/checks?check_run_id=2226440167#step:5:183) we're getting:

> Please check the build arguments.

With a pointer to an `xcodebuild` log file in `/var`, which we can't easily surface in the CI environment for debugging.

I somewhat naively tried [enabling verbose output](https://github.com/ably/ably-asset-tracking-cocoa/pull/130/commits/7d0ee31162c1025f7d4b93d344ff5e5d974cfe30), but that presented no more information.
Another tack will be needed.

**Comment by ben-xD** [comment]
The docs are now being generated successfully @QuintinWillison, but unfortunately the "upload to Amazon S3" step failed with:
```
Run aws s3 sync --acl public-read docs "s3://sdk.ably.com/builds/$GITHUB_REPOSITORY/$DEPLOYMENT_REMOTE_PATH"
fatal error: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
Error: Process completed with exit code 1.
```

**Comment by ben-xD** [comment]
Also, why was `-derivedDataPath` passed to `sourcekitten doc`'s xcode (`--`) argument, I removed it but it doesn’t seem to cause a problem, so I think it's fine to leave it.

**Comment by QuintinWillison** [comment]
Regarding the derived data path, it was something I added in https://github.com/ably/ably-asset-tracking-swift/pull/130/commits/fd89ab941739530e3f4b8a93cc5a979a28bd2643 to try and work out what was going. Therefore, I think you're right - it's not a problem to remove it. 😁

**Review by ben-xD — APPROVED** [review]

**Pull request merged**
