### PR TITLE
Add ability for parsing JSON object (as a dictionary) from presence message

### PR DESCRIPTION
**Pull request by lukasz-szyszkowski**

### CODE REVIEW

**Review by KacperKluka — APPROVED** [review]
LGTM :+1:

**Review by AndyNicks — APPROVED** [review]

**Review by maratal — APPROVED** [review]

**Comment by lawrence-forooghian** [comment]
@lukasz-szyszkowski I'm struggling to understand the problem that this PR is solving, and there's no explanation in the PR description or commit messages. Please could you explain a little?

**Review by lawrence-forooghian — COMMENTED** [review]
@lukasz-szyszkowski I'm struggling to understand the problem that this PR is solving, and there's no explanation in the PR description or commit messages. Please could you explain a little?

**Comment by lukasz-szyszkowski** [comment]
> @lukasz-szyszkowski I'm struggling to understand the problem this PR is solving, and there's no explanation in the PR description or commit messages. Please could you explain a little?

I've linked an issue, but I agree it takes time to dig into the problem. Here is the comment on what's wrong https://github.com/ably/ably-asset-tracking-android/issues/535#issuecomment-993469926

**Pull request merged**
